# nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpIgnorePatterns:
  - ./subgraph
packageExtensions:
  "@urql/core@*":
    dependencies:
      graphql: "*"
  "viem@*":
    dependencies:
      "@types/ws": "*"
      "ws": "*"
      "isomorphic-ws": "*"

  # WalletConnect patch dependencies
  "@walletconnect/iso-crypto@*":
    dependencies:
      "@walletconnect/encoding": "*"
  "@walletconnect/jsonrpc-provider@*":
    dependencies:
      "eventemitter3": "*"
  "@walletconnect/jsonrpc-http-connection@*":
    dependencies:
      "eventemitter3": "*"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
