# nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpIgnorePatterns:
  - ./subgraph
packageExtensions:
  "@urql/core@*":
    dependencies:
      graphql: "*"
  "viem@*":
    dependencies:
      "@types/ws": "*"
      "ws": "*"
      "isomorphic-ws": "*"

  # WalletConnect patch dependencies
  "@walletconnect/auth-client@*":
    dependencies:
      "eventemitter3": "*"
  "@walletconnect/iso-crypto@*":
    dependencies:
      "@walletconnect/encoding": "*"
  "@walletconnect/jsonrpc-provider@*":
    dependencies:
      "eventemitter3": "*"
  "@walletconnect/ethereum-provider@*":
    dependencies:
      "eventemitter3": "*"
  "@walletconnect/ethereum-provider-virtual@*":
    dependencies:
      "eventemitter3": "*"
  "@walletconnect/universal-provider@*":
    dependencies:
      "eventemitter3": "*"
  "@web3modal/ui@*":
    dependencies:
      "lit-html": "*"

  "@web3modal/ethereum@*":
    dependencies:
      "@wagmi/connectors": "*"

  "@walletconnect/legacy-provider@*":
    dependencies:
      "@walletconnect/jsonrpc-utils": "*"
      "eventemitter3": "*"
      "@walletconnect/jsonrpc-types": "*"
      "ws": "*"
  "@walletconnect/legacy-client@*":
    dependencies:
      "ws": "*"

  "@walletconnect/sign-client@*":
    dependencies:
      "lit-html": "*"
      "eventemitter3": "*"
  "@walletconnect/jsonrpc-http-connection@*":
    dependencies:
      "eventemitter3": "*"
  "@walletconnect/types@*":
    dependencies:
      "eventemitter3": "*"
  "@walletconnect/core@*":
    dependencies:
      "eventemitter3": "*"
  "@walletconnect/jsonrpc-ws-connection@*":
    dependencies:
      "eventemitter3": "*"
  "@walletconnect/heartbeat@*":
    dependencies:
      "eventemitter3": "*"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
