[build]
  publish="./frontend/.dist/"
  base = "."
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' netlify-cdp-loader.netlify.app; img-src 'self' blob: data:; script-src 'self' 'unsafe-inline' netlify-cdp-loader.netlify.app; connect-src *; frame-src 'self' app.netlify.com e.widgetbot.io; style-src 'self' 'unsafe-inline';"
